# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import alpha_speaker_pb2 as alpha__speaker__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in alpha_speaker_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AlphaSpeakerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterAlphaSpeaker = channel.unary_unary(
                '/alpha_speaker.AlphaSpeakerService/RegisterAlphaSpeaker',
                request_serializer=alpha__speaker__pb2.SpeakerRegistration.SerializeToString,
                response_deserializer=alpha__speaker__pb2.RegistrationResponse.FromString,
                _registered_method=True)
        self.StreamDeviceStates = channel.unary_stream(
                '/alpha_speaker.AlphaSpeakerService/StreamDeviceStates',
                request_serializer=alpha__speaker__pb2.StateStreamRequest.SerializeToString,
                response_deserializer=alpha__speaker__pb2.DeviceState.FromString,
                _registered_method=True)
        self.SendTextForSpeech = channel.unary_unary(
                '/alpha_speaker.AlphaSpeakerService/SendTextForSpeech',
                request_serializer=alpha__speaker__pb2.TTSRequest.SerializeToString,
                response_deserializer=alpha__speaker__pb2.TTSResponse.FromString,
                _registered_method=True)
        self.StreamTTSCommands = channel.unary_stream(
                '/alpha_speaker.AlphaSpeakerService/StreamTTSCommands',
                request_serializer=alpha__speaker__pb2.StateStreamRequest.SerializeToString,
                response_deserializer=alpha__speaker__pb2.SpeakTextRequest.FromString,
                _registered_method=True)
        self.SendTTSResponse = channel.unary_unary(
                '/alpha_speaker.AlphaSpeakerService/SendTTSResponse',
                request_serializer=alpha__speaker__pb2.SpeakTextResponse.SerializeToString,
                response_deserializer=alpha__speaker__pb2.TTSResponse.FromString,
                _registered_method=True)
        self.SendAlphaCommand = channel.unary_unary(
                '/alpha_speaker.AlphaSpeakerService/SendAlphaCommand',
                request_serializer=alpha__speaker__pb2.AlphaCommand.SerializeToString,
                response_deserializer=alpha__speaker__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.KeepAlive = channel.unary_unary(
                '/alpha_speaker.AlphaSpeakerService/KeepAlive',
                request_serializer=alpha__speaker__pb2.PingRequest.SerializeToString,
                response_deserializer=alpha__speaker__pb2.PingResponse.FromString,
                _registered_method=True)
        self.GetAvailableDevices = channel.unary_unary(
                '/alpha_speaker.AlphaSpeakerService/GetAvailableDevices',
                request_serializer=alpha__speaker__pb2.DeviceListRequest.SerializeToString,
                response_deserializer=alpha__speaker__pb2.DeviceList.FromString,
                _registered_method=True)


class AlphaSpeakerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterAlphaSpeaker(self, request, context):
        """Регистрация Альфа колонки
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamDeviceStates(self, request, context):
        """Потоковая передача состояний устройств
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendTextForSpeech(self, request, context):
        """Отправка текста для TTS (от колонки к HA) - НАПРАВЛЕНИЕ: Колонка → HA
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamTTSCommands(self, request, context):
        """Получение TTS команд от HA - НАПРАВЛЕНИЕ: HA → Колонка
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendTTSResponse(self, request, context):
        """Отправка TTS ответа от колонки
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendAlphaCommand(self, request, context):
        """Отправка команды в HA через создание события
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def KeepAlive(self, request, context):
        """Проверка связи
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAvailableDevices(self, request, context):
        """Получение списка доступных устройств
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AlphaSpeakerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterAlphaSpeaker': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterAlphaSpeaker,
                    request_deserializer=alpha__speaker__pb2.SpeakerRegistration.FromString,
                    response_serializer=alpha__speaker__pb2.RegistrationResponse.SerializeToString,
            ),
            'StreamDeviceStates': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamDeviceStates,
                    request_deserializer=alpha__speaker__pb2.StateStreamRequest.FromString,
                    response_serializer=alpha__speaker__pb2.DeviceState.SerializeToString,
            ),
            'SendTextForSpeech': grpc.unary_unary_rpc_method_handler(
                    servicer.SendTextForSpeech,
                    request_deserializer=alpha__speaker__pb2.TTSRequest.FromString,
                    response_serializer=alpha__speaker__pb2.TTSResponse.SerializeToString,
            ),
            'StreamTTSCommands': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamTTSCommands,
                    request_deserializer=alpha__speaker__pb2.StateStreamRequest.FromString,
                    response_serializer=alpha__speaker__pb2.SpeakTextRequest.SerializeToString,
            ),
            'SendTTSResponse': grpc.unary_unary_rpc_method_handler(
                    servicer.SendTTSResponse,
                    request_deserializer=alpha__speaker__pb2.SpeakTextResponse.FromString,
                    response_serializer=alpha__speaker__pb2.TTSResponse.SerializeToString,
            ),
            'SendAlphaCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.SendAlphaCommand,
                    request_deserializer=alpha__speaker__pb2.AlphaCommand.FromString,
                    response_serializer=alpha__speaker__pb2.CommandResponse.SerializeToString,
            ),
            'KeepAlive': grpc.unary_unary_rpc_method_handler(
                    servicer.KeepAlive,
                    request_deserializer=alpha__speaker__pb2.PingRequest.FromString,
                    response_serializer=alpha__speaker__pb2.PingResponse.SerializeToString,
            ),
            'GetAvailableDevices': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAvailableDevices,
                    request_deserializer=alpha__speaker__pb2.DeviceListRequest.FromString,
                    response_serializer=alpha__speaker__pb2.DeviceList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'alpha_speaker.AlphaSpeakerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('alpha_speaker.AlphaSpeakerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AlphaSpeakerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterAlphaSpeaker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/alpha_speaker.AlphaSpeakerService/RegisterAlphaSpeaker',
            alpha__speaker__pb2.SpeakerRegistration.SerializeToString,
            alpha__speaker__pb2.RegistrationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamDeviceStates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/alpha_speaker.AlphaSpeakerService/StreamDeviceStates',
            alpha__speaker__pb2.StateStreamRequest.SerializeToString,
            alpha__speaker__pb2.DeviceState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendTextForSpeech(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/alpha_speaker.AlphaSpeakerService/SendTextForSpeech',
            alpha__speaker__pb2.TTSRequest.SerializeToString,
            alpha__speaker__pb2.TTSResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamTTSCommands(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/alpha_speaker.AlphaSpeakerService/StreamTTSCommands',
            alpha__speaker__pb2.StateStreamRequest.SerializeToString,
            alpha__speaker__pb2.SpeakTextRequest.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendTTSResponse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/alpha_speaker.AlphaSpeakerService/SendTTSResponse',
            alpha__speaker__pb2.SpeakTextResponse.SerializeToString,
            alpha__speaker__pb2.TTSResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendAlphaCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/alpha_speaker.AlphaSpeakerService/SendAlphaCommand',
            alpha__speaker__pb2.AlphaCommand.SerializeToString,
            alpha__speaker__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def KeepAlive(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/alpha_speaker.AlphaSpeakerService/KeepAlive',
            alpha__speaker__pb2.PingRequest.SerializeToString,
            alpha__speaker__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAvailableDevices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/alpha_speaker.AlphaSpeakerService/GetAvailableDevices',
            alpha__speaker__pb2.DeviceListRequest.SerializeToString,
            alpha__speaker__pb2.DeviceList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
